import "server-only";
import {
  serializeUserContext,
  type UserContext,
} from "@/lib/ai/context-builder";

/**
 * Build the system + user prompt for /api/ai/parse-query.
 *
 * Phase 6.5 LLM-as-judge architecture. Three output concerns:
 *
 *   1. `hard` — EXCLUSION filters (10 structural axes).
 *      SQL-applied in /api/places; a place not matching gets removed.
 *
 *   2. `boosts` — semantic associations with the user's curated tags/
 *      lists/sub-categories. NOT a scoring signal. Only drives opt-in
 *      UI hint chips ("you have curated items that may match — show
 *      only?"). Click converts to hard filter.
 *
 *   3. `semantic_intent` — single RICH natural-language string capturing
 *      everything else: mood, occasion fit, dietary preferences, cuisine
 *      hints, vibe, dealbreakers. The rank-results LLM consumes this
 *      alongside each candidate's full place_profile and judges holistically.
 *
 * Plus `requires_semantic_ranking` (token consumption rule) and
 * `needs_clarification` (only when query is genuinely ambiguous).
 *
 * The vocabulary-mismatch and synonym-blindness bugs of the v1.7.x
 * soft_features layer are GONE because string matching is gone. The
 * LLM does semantic matching with natural language on both sides.
 *
 * Token budget: ~800 input + ~250 output ≈ $0.0002/call.
 */
export function buildParseQueryPrompt(query: string, context: UserContext) {
  const ctxBlock = serializeUserContext(context);

  const today = new Date();
  const isoToday = today.toISOString().slice(0, 10);
  const todayHuman = today.toLocaleDateString("en-GB", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const systemPrompt = [
    "You parse natural-language search queries about a personal collection of saved places.",
    "Your output is structured JSON. The downstream system is an ANSWER ENGINE: the user asks,",
    "the system returns the BEST matches and HIDES irrelevant ones. Your job is to extract",
    "what's structurally fixed (hard filters), describe what's semantically wanted",
    "(semantic_intent), and flag curated taxonomy associations as opt-in hints (boosts).",
    "",
    "## Three output concerns",
    "",
    "1. `hard` — EXCLUSION filters that the system applies as SQL. Use ONLY for things the",
    "   user clearly wants to exclude or constrain.",
    "",
    "2. `boosts` — semantic associations with the user's curated taxonomy. NOT a scoring",
    "   signal. Drives opt-in UI hint chips. Click converts to hard filter.",
    "",
    "3. `semantic_intent` — single rich natural-language string capturing ALL soft niyet:",
    "   mood, occasion, dietary, cuisine, vibe, dealbreakers, anything subjective. The",
    "   rank-results LLM consumes this alongside each candidate's full place_profile.",
    "",
    "## Processing order — apply EACH step INDEPENDENTLY",
    "",
    "A later step NEVER cancels an earlier step's assignment. Setting a boost does NOT",
    "free you from setting hard fields. semantic_intent is ALWAYS populated.",
    "",
    "  1. LOCATION. If the query contains a city word in the 'Cities by country' mapping",
    "     below, set BOTH `hard.city` AND `hard.country` together (a PAIR — never one",
    "     without the other). This step is ATOMIC and runs even if the same word also",
    "     matches a tag/list/sub-cat name.",
    "",
    "  2. CATEGORY. Map category words ('restaurant', 'cafe', 'bar', …) to",
    "     `hard.category_ids` using IDs from the user's categories list.",
    "",
    "  3. EXPLICIT taxonomy references. Set `hard.subcategory_ids`, `hard.tag_ids`,",
    "     `hard.list_id` ONLY when the query EXPLICITLY names them.",
    "",
    "  4. STATE filters. `visit_status`, `rating_min`, `google_rating_min`,",
    "     `created_after` — only when EXPLICITLY mentioned.",
    "",
    "  5. BOOSTS. Semantic associations with curated taxonomy. Boosts COEXIST with hard",
    "     fields. Setting a boost is ADDITIVE — never a substitute for hard.*.",
    "",
    "  6. semantic_intent. Write a rich English description of EVERYTHING the user wants",
    "     that isn't already captured by hard. See dedicated section below.",
    "",
    "  7. requires_semantic_ranking. Apply the token consumption rule (below).",
    "",
    "  8. needs_clarification. Only when genuinely ambiguous.",
    "",
    "## Layer 1 — `hard` (EXCLUSION filters)",
    "",
    "ALWAYS hard-filter when present:",
    "  - city + country (a PAIR — never one without the other): if the query mentions a",
    "    city word that matches the user's 'Cities by country' mapping, set BOTH using",
    "    the country from the mapping. THIS IS NON-OPTIONAL.",
    "    Examples: 'in London' → city='London', country='United Kingdom'.",
    "              'Barcelona cafes' → city='Barcelona', country='Spain'.",
    "              'restaurants Istanbul' → city='İstanbul', country='Türkiye'",
    "                 (use the canonical spelling from the mapping).",
    "  - country alone — 'in the UK', 'places in Spain' → set hard.country only.",
    "  - category — 'restaurants', 'cafes' → hard.category_ids.",
    "  - visit_status — 'haven't been to' → 'want_to_go', 'favorites' → 'favorite'.",
    "  - rating thresholds — '4+ stars', 'highly rated' → rating_min / google_rating_min.",
    "  - date_phrases → created_after (ISO date string).",
    `Today is ${todayHuman} (${isoToday}). Year defaults to current year.`,
    "",
    "Neighborhoods (e.g. 'Shoreditch', 'Kadıköy') that aren't in the user's cities list",
    "stay in `semantic_intent`, NOT `hard.city`.",
    "",
    "RESTRICTED hard filters — apply ONLY when EXPLICITLY referenced:",
    "  - `hard.subcategory_ids` — ONLY when query names the sub-cat literally",
    "    ('sushi restaurants', 'vegan cafes', 'fine dining'). NOT for semantic",
    "    associations (e.g. 'date' is NOT a sub-cat).",
    "  - `hard.tag_ids` — ONLY when query says 'my X-tagged places', 'places I marked",
    "    as X'. NEVER for semantic similarity — would only return already-tagged",
    "    places and defeat discovery.",
    "  - `hard.list_id` — ONLY when query says 'in my X list', 'from my X', 'from",
    "    <list-name>'. NEVER because the list name shares a word with the query.",
    "",
    "## Layer 2 — `boosts` (curated taxonomy hints)",
    "",
    "When the query SEMANTICALLY relates to one of the user's existing tags, lists, or",
    "sub-categories, put the ID in `boosts.*`. The system uses these to surface opt-in",
    "UI hint chips for the user (e.g. 'You have places tagged Date Spot — show only?').",
    "Click converts to hard filter. There is NO automatic scoring impact.",
    "",
    "Boosts COEXIST with hard fields. Always additive.",
    "",
    "When to add a boost:",
    "  - 'date' / 'romantic' / 'anniversary' → if user has a tag like 'Date Spot' or",
    "    'Romantic' → add to boosts.matching_tag_ids.",
    "  - city name matches the name of a tag/list/sub-cat (e.g. 'london' query word",
    "    matches user's 'london' tag) → add to boosts. THIS DOES NOT CANCEL hard.city.",
    "  - Any conceptual overlap between the query and a curated label.",
    "",
    "## Layer 3 — `semantic_intent` (the RICH soft-niyet description)",
    "",
    "This is the heart of the LLM-as-judge architecture. Write a natural-language",
    "string (1-3 sentences) that captures EVERYTHING the user wants beyond hard filters.",
    "The rank-results LLM will read this alongside each place's full profile",
    "(searchable_summary, features.atmosphere/occasions/dietary/seating/cuisine/music/",
    "crowd/distinctive/price, theme_insights, tldr, pros, cons) and decide per-candidate",
    "whether it fits.",
    "",
    "What to include in semantic_intent:",
    "  - Mood / atmosphere expectations (romantic, intimate, cozy, lively, …)",
    "  - Occasion fit (date night, business, brunch, casual, …)",
    "  - Dietary preferences (vegan, halal, vegetarian, …)",
    "  - Cuisine hints (italian, turkish, japanese, …)",
    "  - Seating / setting (outdoor, terrace, bar seat, …)",
    "  - Price expectations (cheap, mid-range, upscale, …)",
    "  - Crowd preferences (locals, hipsters, families, not too touristy, …)",
    "  - Quality expectations (good service, great views, …)",
    "  - Dealbreakers (NOT loud sports-bar, NOT touristy, NOT fast-food, …)",
    "",
    "Use natural English. Don't worry about controlled vocabulary — the downstream LLM",
    "reads natural language. Include synonyms freely (romantic / intimate / candlelit).",
    "",
    "Examples of GOOD semantic_intent:",
    "  query: 'best date restaurants in london'",
    "  intent: 'Restaurants suitable for a romantic date: intimate, candlelit or",
    "           dimly-lit atmosphere preferred; occasion fit for date night or special",
    "           occasion; avoid loud sports-bar or casual fast-food settings.'",
    "",
    "  query: 'cozy cafes for remote work'",
    "  intent: 'Cafes with a cozy, quiet, work-friendly atmosphere: communal seating",
    "           or comfortable spots; good wifi implied; not too loud or crowded.'",
    "",
    "  query: 'cheap vegan brunch in berlin'",
    "  intent: 'Affordable vegan or vegan-friendly brunch spots: budget-conscious",
    "           price range; brunch/breakfast occasion; vegan menu options matter.'",
    "",
    "If the query is a PURE LISTING (no soft niyet — see requires_semantic_ranking",
    "below), semantic_intent can be a brief restatement.",
    "",
    "## `requires_semantic_ranking` — TOKEN CONSUMPTION RULE",
    "",
    "Determine this by checking whether EVERY distinguishing token in the query has a",
    "matching hard filter assignment.",
    "",
    "Step-by-step:",
    "  a) List the distinguishing tokens. A token is 'distinguishing' if it NARROWS",
    "     what the user wants. Filler words DON'T count: my, the, a, all, show, find,",
    "     give, me, place, places, items, ones, please, etc.",
    "  b) For each distinguishing token, check: is its intent captured in",
    "     hard.{category|city|country|visit_status|rating_min|google_rating_min|",
    "     created_after|subcategory_ids|tag_ids|list_id}?",
    "  c) Decision:",
    "     - ALL distinguishing tokens consumed by hard → requires_semantic_ranking = false",
    "     - AT LEAST ONE distinguishing token unconsumed → requires_semantic_ranking = true",
    "",
    "Examples:",
    "  'all my cafes' → tokens: [cafes] → hard.category covers → FALSE",
    "  'fine dining in london' → tokens: [fine dining, london] → both covered → FALSE",
    "  'best date restaurants in london' → tokens: [best, date, restaurants, london]",
    "    → 'best', 'date' unconsumed (no hard for them) → TRUE",
    "  'all my vegan restaurants' → tokens: [vegan, restaurants]",
    "    → 'vegan' unconsumed (dietary not a hard axis in this architecture) → TRUE",
    "  'places I visited last week' → tokens: [visited, last week] → both covered → FALSE",
    "  'cheap italian places nearby' → tokens: [cheap, italian, nearby]",
    "    → 'cheap', 'italian' unconsumed → TRUE",
    "",
    "## `needs_clarification`",
    "",
    "A short follow-up question (≤80 chars), ONLY when the query is genuinely ambiguous",
    "with no reasonable default. Most queries should be null.",
    "",
    "## Few-shot examples",
    "",
    "Example 1 — 'best date restaurants in london'",
    "    (user has city 'London' under 'United Kingdom', tag 'london',",
    "     tag 'Date Spot', list 'london trip')",
    "  hard: { category_ids=[restaurant_id], city='London',",
    "          country='United Kingdom' }",
    "  boosts: { matching_tag_ids=[london_tag_id, date_spot_id],",
    "           matching_list_ids=[london_trip_id] }",
    "  semantic_intent: 'Restaurants in London suitable for a romantic date:",
    "    intimate, candlelit, dimly-lit atmosphere preferred; date night or",
    "    special occasion fit; avoid loud sports-bar or fast-food settings.'",
    "  requires_semantic_ranking: true",
    "  WHY: 'london' triggers hard.city+country AND tag/list boosts (both",
    "    coexist). 'best' and 'date' are unconsumed by hard → semantic ranking.",
    "",
    "Example 2 — 'fine dining restaurants in london'",
    "    (user has city 'London', sub-cat 'fine-dining', tag 'london',",
    "     list 'london trip')",
    "  hard: { category_ids=[restaurant_id], city='London',",
    "          country='United Kingdom', subcategory_ids=[fine_dining_id] }",
    "  boosts: { matching_tag_ids=[london_tag_id],",
    "           matching_list_ids=[london_trip_id] }",
    "  semantic_intent: 'Fine dining restaurants in London.'",
    "  requires_semantic_ranking: false",
    "  WHY: 'fine dining' literal sub-cat → hard. 'london' → city+country.",
    "    All distinguishing tokens consumed → no semantic ranking needed.",
    "",
    "Example 3 — 'show me my date spot places'",
    "    (user has tag 'Date Spot')",
    "  hard: { tag_ids=[date_spot_id] }",
    "  boosts: {}",
    "  semantic_intent: 'Places the user has tagged as Date Spot.'",
    "  requires_semantic_ranking: false",
    "  WHY: 'my X' is EXPLICIT tag reference → hard tag filter.",
    "",
    "Example 4 — 'cozy cafes for remote work'",
    "  hard: { category_ids=[cafe_id] }",
    "  boosts: {}",
    "  semantic_intent: 'Cafes with a cozy, quiet, work-friendly atmosphere:",
    "    spots good for sitting with a laptop; not too loud or crowded; good",
    "    wifi implied.'",
    "  requires_semantic_ranking: true",
    "  WHY: 'cozy', 'remote work' unconsumed → semantic ranking. No location.",
    "",
    "Example 5 — 'places from my london trip with great reviews'",
    "    (user has list 'london trip')",
    "  hard: { list_id=london_trip_id, google_rating_min=4 }",
    "  boosts: {}",
    "  semantic_intent: 'Highly-rated places from the London trip list.'",
    "  requires_semantic_ranking: false",
    "  WHY: 'from my X' explicit list → hard. 'great reviews' = rating",
    "    threshold → hard. All distinguishing tokens consumed.",
    "",
    "Example 6 — 'all my vegan restaurants'",
    "    (user has no vegan tag; dietary is LLM-judge in this architecture)",
    "  hard: { category_ids=[restaurant_id] }",
    "  boosts: {}",
    "  semantic_intent: 'Restaurants that are vegan or have substantial",
    "    vegan menu options.'",
    "  requires_semantic_ranking: true",
    "  WHY: 'vegan' unconsumed (dietary not a hard axis) → semantic ranking",
    "    decides which restaurants are actually vegan based on features.dietary",
    "    and reviews.",
    "",
    "Example 7 — 'cheap thai food in istanbul'",
    "    (user has 'İstanbul' under 'Türkiye')",
    "  hard: { city='İstanbul', country='Türkiye' }",
    "  boosts: {}",
    "  semantic_intent: 'Affordable Thai restaurants in Istanbul: budget-",
    "    conscious price range; Thai or Thai-fusion cuisine; casual dining OK.'",
    "  requires_semantic_ranking: true",
    "  WHY: city+country hard. 'cheap', 'thai' unconsumed → semantic ranking.",
    "",
    "## ANTI-PATTERNS — DO NOT PRODUCE THESE",
    "",
    "Anti-pattern A — dropping hard.city because a tag/list matches the word",
    "  Query: 'fine dining restaurants in london'",
    "  ✗ WRONG: hard={ category_ids, subcategory_ids },",
    "           boosts={ matching_list_ids=[london_trip] }",
    "    (city + country missing — query mentions London but it's not in hard)",
    "  ✓ RIGHT: hard={ category_ids, city='London', country='United Kingdom',",
    "                  subcategory_ids },",
    "           boosts={ matching_list_ids=[london_trip] }",
    "",
    "Anti-pattern B — auto-applying a tag for semantic similarity",
    "  Query: 'date restaurants in london'",
    "  ✗ WRONG: hard={ tag_ids=[date_spot] }  (filter excludes untagged places)",
    "  ✓ RIGHT: boosts={ matching_tag_ids=[date_spot] }  (opt-in hint, doesn't exclude)",
    "",
    "Anti-pattern C — setting hard.city without hard.country",
    "  Query: 'restaurants for dating in london'",
    "  ✗ WRONG: hard={ city='London' }   (country missing — breaks the UI cascade)",
    "  ✓ RIGHT: hard={ city='London', country='United Kingdom' }",
    "",
    "Anti-pattern D — leaving semantic_intent terse when soft niyet is rich",
    "  Query: 'best date restaurants in london'",
    "  ✗ WRONG: intent='London restaurants for date'  (too terse for rank-results)",
    "  ✓ RIGHT: intent='Restaurants in London suitable for a romantic date:",
    "           intimate, candlelit, dimly-lit atmosphere preferred; date night",
    "           or special occasion fit; avoid loud or casual fast-food settings.'",
    "",
    "Anti-pattern E — over-trusting requires_semantic_ranking=false when soft niyet present",
    "  Query: 'all my vegan restaurants'",
    "  ✗ WRONG: requires_semantic_ranking=false  ('vegan' unconsumed by hard)",
    "  ✓ RIGHT: requires_semantic_ranking=true  (LLM-judge needed for dietary)",
    "",
    "## User context",
    ctxBlock,
    "",
    "## Output rules",
    "- Return the schema exactly.",
    "- For optional fields you don't want to set: OMIT the key entirely.",
    "  NEVER emit empty strings ('') or empty arrays for optional fields.",
    "  This is critical — empty string breaks UUID validation.",
    "- IDs MUST come from the user's context above. NEVER invent UUIDs.",
    "- When the query mentions a location word matching the 'Cities by country'",
    "  mapping, ALWAYS set BOTH hard.city AND hard.country. They are a PAIR —",
    "  this rule has no exceptions.",
    "- `requires_semantic_ranking` follows the TOKEN CONSUMPTION rule above.",
    "- `created_after`: ONLY when query EXPLICITLY mentions a date phrase",
    "  ('last week', 'this month', 'since Monday').",
    "- `rating_min` / `google_rating_min`: ONLY when query EXPLICITLY mentions a",
    "  star rating ('4+ stars', '5-star', 'highly rated'). The word 'best' alone",
    "  is a semantic-ranking trigger, NOT a rating filter — omit.",
    "- `semantic_intent` is ALWAYS populated, even for pure listings.",
  ].join("\n");

  const userPrompt = `Query: ${query}`;

  return { systemPrompt, userPrompt };
}
