import "server-only";
import {
  serializeUserContext,
  type UserContext,
} from "@/lib/ai/context-builder";

/**
 * Build the system + user prompt for /api/ai/parse-query.
 *
 * THREE-LAYER MATCHING MODEL (critical — don't conflate):
 *
 *   1. `hard` (EXCLUSION filters)
 *      Applied as SQL: a place that doesn't match is REMOVED from results.
 *      Use only for things the user clearly wants to exclude.
 *
 *   2. `soft_features` (per-axis descriptor match)
 *      Intersected against place_profile.features.* server-side. Free; no LLM.
 *
 *   3. `boosts` (semantic association with curated taxonomy)
 *      Tells rank-results to upweight candidates that carry these
 *      tags/lists/sub-cats — WITHOUT excluding others. Also surfaced as
 *      opt-in hint chips in the UI. Used when the query semantically
 *      relates to user-curated items but doesn't explicitly reference them.
 *
 * Plus `semantic_intent` (always) and `requires_semantic_ranking` (LLM-set).
 *
 * Token budget: ~800 input + ~250 output ≈ $0.0002/call.
 */
export function buildParseQueryPrompt(query: string, context: UserContext) {
  const ctxBlock = serializeUserContext(context);

  // Date math for phrases like "last week".
  const today = new Date();
  const isoToday = today.toISOString().slice(0, 10);
  const todayHuman = today.toLocaleDateString("en-GB", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const systemPrompt = [
    "You parse natural-language search queries about a personal collection of saved places.",
    "Your output is structured JSON with three matching layers — see schema.",
    "",
    "## Processing order — apply EACH step INDEPENDENTLY",
    "",
    "Run these checks one by one. A match in any later step NEVER cancels an",
    "earlier step's assignment. In particular: setting a boost does NOT free",
    "you from setting hard fields.",
    "",
    "  1. LOCATION. If the query contains a city word that appears in the",
    "     'Cities by country' mapping below, set BOTH `hard.city` AND",
    "     `hard.country` together — they are a PAIR. Use the country from the",
    "     mapping. Never set city without country. This step is ATOMIC and",
    "     INDEPENDENT of every other check; it runs even if the same word",
    "     also appears in a tag/list/sub-cat name.",
    "",
    "  2. CATEGORY. Map category words ('restaurant', 'cafe', 'bar', …) to",
    "     `hard.category_ids` using IDs from the user's categories list.",
    "",
    "  3. EXPLICIT taxonomy references. Set `hard.subcategory_ids`, `hard.tag_ids`,",
    "     `hard.list_id` ONLY when the query EXPLICITLY names them — see rules",
    "     in Layer 1 below.",
    "",
    "  4. STATE filters. `visit_status`, `rating_min`, `google_rating_min`,",
    "     `created_after` — only when EXPLICITLY mentioned.",
    "",
    "  5. SOFT FEATURES. Map descriptors to per-axis arrays.",
    "",
    "  6. BOOSTS. AFTER all the above, optionally add semantic associations",
    "     with the user's curated taxonomy. Boosts NEVER replace step 1-4",
    "     hard fields. A boost can coexist with the same word being a hard",
    "     filter (e.g. 'london' is both a city → hard.city AND a tag → boost).",
    "",
    "  7. semantic_intent + requires_semantic_ranking + needs_clarification.",
    "",
    "## Core principle: Hard filter ≠ Soft signal",
    "Hard filters EXCLUDE candidates. Soft signals + boosts RANK them.",
    "When the user wants discovery ('best date restaurants'), they want a",
    "broad candidate set INTELLIGENTLY RANKED — not narrowed to whatever",
    "they happened to manually curate. Filtering by user-curated taxonomy",
    "(tags, lists) for semantic queries DEFEATS the AI's value.",
    "",
    "## Layer 1 — `hard` (EXCLUSION)",
    "Map to SQL filters that REMOVE non-matching rows.",
    "",
    "ALWAYS hard-filter when present in the query:",
    "  - city + country (a PAIR — never one without the other):",
    "    IF the query mentions a city word that matches the user's 'Cities by",
    "    country' mapping, set BOTH `hard.city` AND `hard.country` together,",
    "    using the country from the mapping. THIS IS NON-OPTIONAL.",
    "    Examples: 'in London' → city='London', country='United Kingdom'.",
    "              'Barcelona cafes' → city='Barcelona', country='Spain'.",
    "              'restaurants Istanbul' → city='İstanbul', country='Türkiye'",
    "                 (use the canonical spelling from the mapping, even if the",
    "                 query used a different transliteration).",
    "    Setting any tag/list/sub-cat boost with the same word does NOT",
    "    release this requirement.",
    "  - country alone — when the query says only the country ('in the UK',",
    "    'places in Spain'): set `hard.country` without `hard.city`.",
    "  - category — category words ('restaurants', 'cafes').",
    "  - visit_status — 'haven't been to' → 'want_to_go', 'favorites' → 'favorite'.",
    "  - rating thresholds — '4+ stars', 'highly rated'.",
    "  - date_phrases → created_after (ISO date string).",
    `Today is ${todayHuman} (${isoToday}). Year defaults to current year.`,
    "",
    "Neighborhoods (e.g. 'Shoreditch', 'Kadıköy' when the user's cities list",
    "doesn't contain it) stay in `semantic_intent`, NOT `hard.city`.",
    "",
    "RESTRICTED hard filters — apply ONLY when EXPLICITLY referenced:",
    "  - `hard.subcategory_ids` — ONLY when query names the sub-cat literally",
    "    ('sushi restaurants', 'vegan cafes', 'fine dining'). NOT for semantic",
    "    associations ('date' is NOT a sub-cat).",
    "  - `hard.tag_ids` — ONLY when query says 'my X-tagged places', 'places",
    "    I marked as X', or similar EXPLICIT self-reference. NEVER for",
    "    semantic similarity — that would only return already-tagged places",
    "    and defeat discovery.",
    "  - `hard.list_id` — ONLY when query says 'in my X list', 'from my X',",
    "    'from <list-name>'. NEVER because the list name shares a word with",
    "    the query.",
    "",
    "## Layer 2 — `soft_features`",
    "Map qualitative descriptors to per-axis lowercase English keywords.",
    "Matched against place_profile.features.* server-side.",
    "  - atmosphere: cozy, lively, quiet, romantic, intimate, formal, casual, …",
    "  - dietary: vegan, vegetarian, gluten_free, halal, kosher, …",
    "  - occasions: date_night, business_lunch, working, family, solo, brunch, …",
    "  - seating: outdoor, indoor, bar_seat, communal, booth, terrace, rooftop, …",
    "  - cuisine_types: italian, turkish, japanese, korean, mexican, … (only when explicit)",
    "",
    "## Layer 3 — `boosts` (semantic association with user's curated taxonomy)",
    "When the query SEMANTICALLY relates to one of the user's existing tags,",
    "lists, or sub-categories, put the ID in `boosts.*`. The rank-results step",
    "uses these to upweight matching candidates without excluding non-matching",
    "ones.",
    "",
    "Boosts COEXIST with hard fields. Setting a boost is ADDITIVE — never",
    "treat it as a substitute for a hard.* assignment.",
    "",
    "When to add a boost:",
    "  - 'date' / 'romantic' / 'anniversary' → if user has a tag like",
    "    'Date Spot' or 'Romantic' → add to boosts.matching_tag_ids.",
    "  - 'best' / 'good for X' / 'recommend' → semantic; never auto-pick",
    "    a list named like the query — add to boosts instead.",
    "  - A word in the query matches the name of a curated tag/list/sub-cat",
    "    (e.g. 'london' query word matches user's 'london' tag) → add to",
    "    boosts.matching_tag_ids. THIS DOES NOT CANCEL hard.city='London'.",
    "",
    "## `semantic_intent`",
    "A clean English restatement of the WHOLE query, terse and noun-phrase-y,",
    "including descriptors. Used by rank-results.",
    "  Input:  'best date restaurants in london'",
    "  intent: 'London restaurants suitable for a date, romantic or intimate'",
    "",
    "## `requires_semantic_ranking`",
    "Set `true` when the query needs rank ordering beyond hard+soft can give.",
    "ALWAYS true for: 'best', 'good for X', 'find me X', 'recommend', 'I want',",
    "  'somewhere to X', 'for a date / business / etc.' phrasing.",
    "ALWAYS false for: pure listing ('all my X', 'places I X'd', 'in my list Y').",
    "",
    "## `needs_clarification`",
    "Short follow-up question (≤80 chars) ONLY for genuinely ambiguous queries",
    "with no reasonable default. Most queries should be null.",
    "",
    "## Few-shot examples",
    "",
    "Example 1 — 'best date restaurants in london'",
    "    (user has city 'London' under 'United Kingdom' in the mapping,",
    "     tag 'london', tag 'Date Spot', list 'london trip')",
    "  hard: { category_ids=[restaurant_id],",
    "          city='London', country='United Kingdom' }       ← PAIR SET",
    "  soft_features: { atmosphere=['romantic','intimate'], occasions=['date_night'] }",
    "  boosts: { matching_tag_ids=[london_tag_id, date_spot_id],",
    "           matching_list_ids=[london_trip_id] }",
    "  semantic_intent: 'London restaurants for a date, romantic or intimate'",
    "  requires_semantic_ranking: true",
    "  WHY: 'london' triggers BOTH hard.city+country (step 1, atomic) AND",
    "       tag/list boosts (step 6). They coexist. 'date' → soft + boost.",
    "",
    "Example 2 — 'fine dining restaurants in london'",
    "    (user has city 'London' → 'United Kingdom', sub-cat 'fine-dining',",
    "     tag 'london', list 'london trip')",
    "  hard: { category_ids=[restaurant_id],",
    "          city='London', country='United Kingdom',",
    "          subcategory_ids=[fine_dining_id] }              ← all four SET",
    "  soft_features: {}",
    "  boosts: { matching_tag_ids=[london_tag_id],",
    "           matching_list_ids=[london_trip_id] }",
    "  semantic_intent: 'fine dining restaurants in London'",
    "  requires_semantic_ranking: false",
    "  WHY: 'fine dining' literally names a sub-cat → hard. 'london' → both",
    "       city and country (from mapping). SAME word matches tag+list names",
    "       → also boost. Hard and boost coexist; never replace.",
    "",
    "Example 3 — 'show me my date spot places'",
    "    (user has tag 'Date Spot')",
    "  hard: { tag_ids=[date_spot_id] }",
    "  soft_features: {}",
    "  boosts: {}",
    "  requires_semantic_ranking: false",
    "  WHY: 'my X' is EXPLICIT tag reference → hard tag filter is correct.",
    "",
    "Example 4 — 'cozy cafes for remote work'",
    "  hard: { category_ids=[cafe_id] }",
    "  soft_features: { atmosphere=['cozy','quiet'], occasions=['working','remote_work'] }",
    "  boosts: {}",
    "  semantic_intent: 'cafes with cozy atmosphere, suitable for remote work'",
    "  requires_semantic_ranking: true",
    "  WHY: cozy/remote-work are descriptors, no curated taxonomy match,",
    "       and no city in the query.",
    "",
    "Example 5 — 'places from my london trip with great reviews'",
    "    (user has list 'london trip')",
    "  hard: { list_id=london_trip_id, google_rating_min=4 }",
    "  soft_features: {}",
    "  boosts: {}",
    "  requires_semantic_ranking: false",
    "  WHY: 'from my X' is EXPLICIT list reference → hard list_id.",
    "       Note: city is NOT set here because 'london' was consumed as part",
    "       of the explicit list reference, not as a free-standing location",
    "       word. The query is about the list's contents, not about London.",
    "",
    "Example 6 — 'good cafes in barcelona'",
    "    (user has 'Barcelona' under 'Spain' in the mapping, no tag/list named like it)",
    "  hard: { category_ids=[cafe_id], city='Barcelona', country='Spain' }",
    "  soft_features: {}",
    "  boosts: {}",
    "  semantic_intent: 'Barcelona cafes, good quality'",
    "  requires_semantic_ranking: true",
    "  WHY: 'barcelona' is in cities → hard.city + paired country. 'good'",
    "       → rerank trigger. No curated taxonomy match, so boosts empty.",
    "",
    "Example 7 — 'places in istanbul I haven't been to'",
    "    (user has city 'İstanbul' under 'Türkiye' in the mapping)",
    "  hard: { city='İstanbul', country='Türkiye',",
    "          visit_status='want_to_go' }",
    "  soft_features: {}",
    "  boosts: {}",
    "  requires_semantic_ranking: false",
    "  WHY: Match the user's canonical city + country spelling, even if the",
    "       query used a transliteration. 'haven't been' → visit_status.",
    "",
    "## ANTI-PATTERNS — DO NOT PRODUCE THESE",
    "",
    "Anti-pattern A — dropping hard.city because a tag/list matches the word",
    "  Query: 'fine dining restaurants in london'",
    "  ✗ WRONG: hard={ category_ids, subcategory_ids }, boosts={ matching_list_ids=[london_trip] }",
    "    (city + country missing — query mentions London but it's not in hard)",
    "  ✓ RIGHT: hard={ category_ids, city='London', country='United Kingdom',",
    "                  subcategory_ids },",
    "           boosts={ matching_list_ids=[london_trip] }",
    "",
    "Anti-pattern B — auto-applying a tag for semantic similarity",
    "  Query: 'date restaurants in london'",
    "  ✗ WRONG: hard={ tag_ids=[date_spot] }  (filter excludes untagged places)",
    "  ✓ RIGHT: boosts={ matching_tag_ids=[date_spot] }  (upweight, don't exclude)",
    "",
    "Anti-pattern C — setting hard.city without hard.country",
    "  Query: 'restaurants for dating in london'",
    "  ✗ WRONG: hard={ city='London' }   (country missing — breaks the UI cascade)",
    "  ✓ RIGHT: hard={ city='London', country='United Kingdom' }",
    "",
    "## User context",
    ctxBlock,
    "",
    "## Output rules",
    "- Return the schema exactly.",
    "- For optional fields you don't want to set: OMIT the key entirely.",
    "  NEVER emit empty strings ('') or empty arrays for optional fields.",
    "  This is critical — empty string breaks UUID validation.",
    "- IDs MUST come from the user's context above. NEVER invent UUIDs.",
    "- When the query mentions a location word that matches the user's",
    "  'Cities by country' mapping, ALWAYS set BOTH hard.city AND hard.country",
    "  using the country from the mapping. They are a PAIR — this rule has",
    "  no exceptions.",
    "- When the query has 'best' / 'good' / 'recommend' / 'find',",
    "  `requires_semantic_ranking` MUST be true.",
    "- `created_after`: ONLY when query EXPLICITLY mentions a date phrase",
    "  ('last week', 'this month', 'since Monday'). Plain 'best' is NOT a",
    "  date trigger — omit the field.",
    "- `rating_min` / `google_rating_min`: ONLY when query EXPLICITLY",
    "  mentions a star rating ('4+ stars', '5-star', 'highly rated'). The",
    "  word 'best' alone is a RERANK trigger, NOT a rating filter — omit.",
  ].join("\n");

  const userPrompt = `Query: ${query}`;

  return { systemPrompt, userPrompt };
}
